#ifndef __ID_H
#define __ID_H

#define GUI_ID_BUTTON_OUTPUT GUI_ID_USER + 0x01
#define GUI_ID_BUTTON_ANGLE  GUI_ID_USER + 0x02
#define GUI_ID_BUTTON_ADD    GUI_ID_USER + 0x03
#define GUI_ID_BUTTON_SUB    GUI_ID_USER + 0x04
#define GUI_ID_BUTTON_SET    GUI_ID_USER + 0x05
#define GUI_ID_BUTTON_SAVE   GUI_ID_USER + 0x06
#define GUI_ID_BUTTON_NUM1   GUI_ID_USER + 0x07
#define GUI_ID_BUTTON_NUM2   GUI_ID_USER + 0x08
#define GUI_ID_BUTTON_NUM3   GUI_ID_USER + 0x09
#define GUI_ID_BUTTON_NUM4   GUI_ID_USER + 0x0A
#define GUI_ID_BUTTON_NUM5   GUI_ID_USER + 0x0B
#define GUI_ID_BUTTON_NUM6   GUI_ID_USER + 0x0C
#define GUI_ID_BUTTON_NUM7   GUI_ID_USER + 0x0D
#define GUI_ID_BUTTON_NUM8   GUI_ID_USER + 0x0E
#define GUI_ID_BUTTON_NUM9   GUI_ID_USER + 0x0F
#define GUI_ID_BUTTON_NUM0   GUI_ID_USER + 0x10
#define GUI_ID_BUTTON_CLR    GUI_ID_USER + 0x11
#define GUI_ID_BUTTON_OK     GUI_ID_USER + 0x12
#define GUI_ID_BUTTON_CANCEL       GUI_ID_USER + 0x13
#define GUI_ID_BUTTON_TIME_OK      GUI_ID_USER + 0x14
#define GUI_ID_BUTTON_TIME_CAVCEL  GUI_ID_USER + 0x15
#define GUI_ID_BUTTON_BK_SPC     GUI_ID_USER + 0x16


#define GUI_ID_TEXT_SPEED    GUI_ID_USER + 0x30
#define GUI_ID_TEXT_ANGLE    GUI_ID_USER + 0x31
#define GUI_ID_TEXT_TITLE    GUI_ID_USER + 0x32
#define GUI_ID_TEXT_TIME     GUI_ID_USER + 0x33
#define GUI_ID_TEXT_YEAR     GUI_ID_USER + 0x34
#define GUI_ID_TEXT_MONTH    GUI_ID_USER + 0x35
#define GUI_ID_TEXT_DATE     GUI_ID_USER + 0x36
#define GUI_ID_TEXT_HOUR     GUI_ID_USER + 0x37
#define GUI_ID_TEXT_MIN      GUI_ID_USER + 0x38
#define GUI_ID_TEXT_SEC      GUI_ID_USER + 0x39

#define GUI_ID_EDIT_SPEED       GUI_ID_USER + 0x60
#define GUI_ID_EDIT_ANGLE       GUI_ID_USER + 0x61
#define GUI_ID_EDIT_KB_INPUT    GUI_ID_USER + 0x62
#define GUI_ID_EDIT_YEAR        GUI_ID_USER + 0x63
#define GUI_ID_EDIT_MONTH       GUI_ID_USER + 0x64
#define GUI_ID_EDIT_DATE        GUI_ID_USER + 0x65
#define GUI_ID_EDIT_HOUR        GUI_ID_USER + 0x66
#define GUI_ID_EDIT_MIN         GUI_ID_USER + 0x67
#define GUI_ID_EDIT_SEC         GUI_ID_USER + 0x68


#define GUI_ID_BUTTON_OD1     GUI_ID_USER + 0x100
#define GUI_ID_BUTTON_OD2     GUI_ID_USER + 0x101
#define GUI_ID_BUTTON_WG     GUI_ID_USER + 0x103

//==================================================================
#define GUI_ID_BUTTON_DATA_SET_YA     GUI_ID_USER + 0x200
#define GUI_ID_BUTTON_DATA_SET_YS     GUI_ID_USER + 0x201
#define GUI_ID_BUTTON_DATA_SET_YTEXT  GUI_ID_USER + 0x202

#define GUI_ID_BUTTON_DATA_SET_MA     GUI_ID_USER + 0x203
#define GUI_ID_BUTTON_DATA_SET_MS     GUI_ID_USER + 0x204
#define GUI_ID_BUTTON_DATA_SET_MTEXT  GUI_ID_USER + 0x205

#define GUI_ID_BUTTON_DATA_SET_DA     GUI_ID_USER + 0x206
#define GUI_ID_BUTTON_DATA_SET_DS     GUI_ID_USER + 0x207
#define GUI_ID_BUTTON_DATA_SET_DTEXT  GUI_ID_USER + 0x208

//==================================================================
#define GUI_ID_BUTTON_TIME_SET_HA     GUI_ID_USER + 0x220
#define GUI_ID_BUTTON_TIME_SET_HS     GUI_ID_USER + 0x221
#define GUI_ID_BUTTON_TIME_SET_HTEXT  GUI_ID_USER + 0x222

#define GUI_ID_BUTTON_TIME_SET_MA     GUI_ID_USER + 0x223
#define GUI_ID_BUTTON_TIME_SET_MS     GUI_ID_USER + 0x224
#define GUI_ID_BUTTON_TIME_SET_MTEXT  GUI_ID_USER + 0x225

#define GUI_ID_BUTTON_TIME_SET_SA     GUI_ID_USER + 0x226
#define GUI_ID_BUTTON_TIME_SET_SS     GUI_ID_USER + 0x227
#define GUI_ID_BUTTON_TIME_SET_STEXT  GUI_ID_USER + 0x228


#define GUI_ID_BUTTON_TIME_SET_OK      GUI_ID_USER + 0x240
#define GUI_ID_BUTTON_TIME_SET_CANCEL  GUI_ID_USER + 0x241

#define GUI_ID_TEXT_TIME_SET_TIME      GUI_ID_USER + 0x242
#define GUI_ID_TEXT_TIME_SET_DATE      GUI_ID_USER + 0x243

#define GUI_ID_EDIT_TEST_PWM      GUI_ID_USER + 0x245
#define GUI_ID_EDIT_TEST_PWM1      GUI_ID_USER + 0x246


#define GUI_ID_MAIN_DLG     GUI_ID_USER + 0x300
#define GUI_ID_SFKB_DLG     GUI_ID_USER + 0x301
#define GUI_ID_SET_DLG      GUI_ID_USER + 0x302
#define GUI_ID_TS_CLB_DLG   GUI_ID_USER + 0x303


#define   WM_USER_MSG1                   WM_USER + 0x100 
#define   WM_USER_MSG2                   WM_USER + 0x101
#define   WM_USER_SHOW_TIME              WM_USER + 0x102
#define   WM_USER_SHOW_PWM              WM_USER + 0x104

#define   WM_USER_SFKB_END               WM_USER + 0x103

#endif
